Sc 20424 otel contrib branch
sematext/opentelemetry-collector-contrib pull request #6
Opened 2024-12-23 21:14 UTC by AkhigbeEromo

#### Description

#### Link to tracking issue
Fixes

#### Testing

#### Documentation

2024-12-23 21:34 UTC, AkhigbeEromo commented
This is how the first PR for Doris Exporter looked like:
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33790
The main details should actually go to the issue, not the PRs, once we are sure everything is good with logs support I will update our issue with information from the logs side of things

2025-01-09 15:35 UTC, cpipilas requested changes
left comments

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/README.md
> +* `app_token` App token specifies the token of Sematext Monitoring App to which the user wants to send data to.
We need to specify the format of app_token here

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/README.md
> +  app_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
this is an example, an actual (but dummy) App Token should be used

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/README.md
> +  app_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
same here

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/config.go
> +	appTokenLength    = 36
why is this needed?

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/config.go
> +	// App token is the token of Sematext Monitoring App to which you want to send the logs.
Logs App

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/config.go
> +	if len(cfg.MetricsConfig.AppToken) != appTokenLength {
only length is validated?

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/config_test.go
> +					AppToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
is this going to be accepted without valid App token?

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/doc.go
> +// Package sematextexporter sends metrics to sematext cloud.
and logs

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/testdata/config.yaml
> +    app_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
new line at the EOL

2025-01-09 15:35 UTC, cpipilas commented on exporter/sematextexporter/metadata.yaml
> +    active: [AkhigbeEromo]
can we add more codeowners?

2025-01-09 16:26 UTC, AkhigbeEromo commented on exporter/sematextexporter/config.go
> +	appTokenLength    = 36
The constants are needed for the validate function and Akshat advised it is not good practice to hardcode raw values into code

2025-01-09 16:27 UTC, AkhigbeEromo commented on exporter/sematextexporter/config.go
> +	if len(cfg.MetricsConfig.AppToken) != appTokenLength {
What other validation do we need?

2025-01-09 16:29 UTC, AkhigbeEromo commented on exporter/sematextexporter/config_test.go
> +					AppToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
Yes, this is just a test. But I can put a dummy app token there, it will not cause an issue

2025-01-09 16:29 UTC, AkhigbeEromo commented on exporter/sematextexporter/metadata.yaml
> +    active: [AkhigbeEromo]
Who else, should I add ?

2025-01-10 09:14 UTC, AkhigbeEromo commented on exporter/sematextexporter/metadata.yaml
> +    active: [AkhigbeEromo]
@cpipilas

2025-01-10 09:45 UTC, cpipilas commented on exporter/sematextexporter/metadata.yaml
> +    active: [AkhigbeEromo]
Akshat & Bora

2025-01-10 10:10 UTC, AkhigbeEromo commented on exporter/sematextexporter/config.go
> +	if len(cfg.MetricsConfig.AppToken) != appTokenLength {
@cpipilas

2025-01-10 11:03 UTC, cpipilas commented on exporter/sematextexporter/README.md
> +* `app_token` App token specifies the token of Sematext Monitoring App to which the user wants to send data to.
or better say that follows the UUID standard

2025-01-10 11:05 UTC, cpipilas commented on exporter/sematextexporter/config.go
> +	if len(cfg.MetricsConfig.AppToken) != appTokenLength {
Something like 

```go
...
	if !isValidUUID(cfg.MetricsConfig.AppToken) {
		return fmt.Errorf("invalid metrics app_token: %s. app_token is not a valid UUID", cfg.MetricsConfig.AppToken)
	}
...

func isValidUUID(uuid string) bool {
	const uuidPattern = `^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`
	return regexp.MustCompile(uuidPattern).MatchString(strings.ToLower(uuid))
}
```

2025-01-10 11:21 UTC, AkhigbeEromo commented on exporter/sematextexporter/config_test.go
> +					AppToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
Tried using a dummy app token and I got this error
![Screenshot 2025-01-10 at 11 17 05](https://github.com/user-attachments/assets/b4c7dbf1-5a86-4d96-89e6-fb06c6703203)

2025-01-10 11:26 UTC, cpipilas commented on exporter/sematextexporter/config.go
> +	appTokenLength    = 36
if UUID validation is done as suggested, I don't think we need appTokenLength

2025-01-10 11:27 UTC, cpipilas commented on exporter/sematextexporter/config.go
> +	if len(cfg.MetricsConfig.AppToken) != appTokenLength {
@AkhigbeEromo please first go through all the comments and then request for a review, this is pending

2025-01-10 11:27 UTC, cpipilas commented on exporter/sematextexporter/config_test.go
> +					AppToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
So what is the action here, decide.

2025-01-10 12:34 UTC, AkhigbeEromo commented on exporter/sematextexporter/config_test.go
> +					AppToken: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
Replace with xxxx

2025-01-10 12:42 UTC, AkhigbeEromo commented on exporter/sematextexporter/config.go
> +	if len(cfg.MetricsConfig.AppToken) != appTokenLength {
@cpipilas using this will mean I will have to actually hardcode dummy token values and that will be an issue

2025-01-10 12:52 UTC, cpipilas commented on exporter/sematextexporter/config.go
> +	if len(cfg.MetricsConfig.AppToken) != appTokenLength {
If that is the case, the validation will be dummy as well.

2025-01-10 16:05 UTC, cpipilas approved these changes
I don't have anything more to comment.

2025-01-13 07:58 UTC, closed without merging